export const courses = [
  "ACC Accounting",
  "ADM Apparel Design and Merchandising",
  "AED Art Education",
  "AEM Applied Engineering Management",
  "AFA African/African-American Studies",
  "AFS Aerospace Studies",
  "AGR Agriculture",
  "ANS Animal Studies",
  "ANT Anthropology",
  "APP Appalachian Studies",
  "APS Assets Protection",
  "ARH Art History",
  "ART Art",
  "ASL American Sign Language",
  "ASO Arts and Sciences Orientation",
  "AST Astronomy",
  "ATR Athletic Training",
  "AVN Aviation",
  "BEM Broadcasting and Electronic Media",
  "BIO Biology",
  "BTO Business and Technology Orientation",
  "BTS Business and Technology Seminar",
  "CCT Corporate Communication and Technology",
  "CDF Child and Family Studies",
  "CDS Communication Disorders and Sciences",
  "CHE Chemistry",
  "CHS Health Sciences Interdisciplinary",
  "CIS Computer Information Systems",
  "CLS Clinical Laboratory Science",
  "CLT Clinical Laboratory Technology",
  "CMS Communication Studies",
  "CNM Arts and Science Interdisciplinary",
  "COM Communications",
  "CON Construction Management",
  "COR Correctional and Juvenile Studies",
  "COU Counselor Education",
  "CRJ Criminal Justice",
  "CSC Computer Science",
  "CTE Career and Technical Education",
  "DES Design",
  "EAD Educational Administration",
  "ECO Economics",
  "EDC Educational Core",
  "EDF Educational Studies",
  "EDL ED Leadership and Policy Studies",
  "EDO Academic Orientation",
  "EET Electricity/Electronic Technology",
  "EGC Education Grad Cert",
  "EHS Environmental Health Sciences",
  "ELE Elementary Education",
  "EMC Emergency Medical Care",
  "EME Elementary/Middle Grade",
  "EMG Middle Grade Education",
  "EMS Elementary/Middle Grade/Secondary Education",
  "ENG English and Theatre",
  "ENR Learning Skills",
  "ENW English Creative Writing",
  "EPY Educational Psychology",
  "ESE Secondary Education",
  "ETL Education-Teacher Leader",
  "FCC Foreign Culture and Civilization",
  "FCS Family and Consumer Sciences",
  "FIN Finance",
  "FLS Foreign Language Studies",
  "FOR Forensic Science",
  "FRE French",
  "FRM Family Resource Management",
  "FSE Fire and Safety Engineering Technology",
  "GBU General Business",
  "GCM Graphic Communications Management",
  "GCS Interpersonal Skills/Career Counseling",
  "GEO Geography",
  "GER German",
  "GLY Geology",
  "GSD Student Development",
  "GSO Orientation for Undeclared Students",
  "Grad Degree Exit Requirement N/A",
  "HEA Health Education",
  "HIS History",
  "HLS Homeland Security",
  "HON Honors Program",
  "HSA Health Service Administration",
  "HSO Health Services Orientation",
  "HUM Humanities",
  "INS Insurance",
  "ITP Interpreter Training",
  "JOU Journalism",
  "JPN Japanese",
  "JSO Justice and Safety Orientation",
  "LAS Paralegal",
  "LAT Latin",
  "LIB Library Science",
  "MAE Mathematics Education",
  "MAT Mathematics",
  "MGT Management",
  "MKT Marketing",
  "MPH Public Health",
  "MSL Military Science and Leadership",
  "MUH Music History",
  "MUS Music",
  "NAT Natural Science",
  "NET Networking",
  "NFA Nutrition/Foods/Food Administration",
  "NUR Associate Nursing",
  "Nursing N/A",
  "OHO Ornamental Horticulture",
  "OSH Occupational Safety",
  "OTS Occupational Therapy",
  "PHE Physical Education",
  "PHI Philosophy",
  "PHY Physics",
  "PLI Prof Liability Insurance",
  "PLS Police Studies",
  "POL Political Science",
  "PSY Psychology",
  "PUB Public Relations",
  "QMB Quantitative Methods",
  "REC Recreation/Park Administration",
  "REL Religion",
  "SED Special Education",
  "SOC Sociology",
  "SPA Spanish",
  "SSE Safety, Security and Emg Mgt",
  "STA Statistics",
  "SWK Social Work",
  "TEC Technology, General",
  "THE Theatre Arts",
  "TRS Traffic Safety",
  "VTS Veterans Studies",
  "WGS Women and Gender Studies",
];

export const courseAbbreviations = Object.fromEntries(
  courses.map((course) => [
    course.split(" ").slice(1).join(" "),
    course.split(" ")[0],
  ])
);

export const abbreviateCourse = ({ name }) => courseAbbreviations[name];
